### ISSUE TITLE
Ipv4 and Ipv6 WAN IP

### ISSUE THREAD

**Issue by EduFrazao** [k44sh/rutorrent#10]
Hi.
The automatic WAN IP Detection is for Ipv4 and Ipv6?
Thank you!

**Comment by EduFrazao** [comment]
I managed to get it working:
Fist I create a new docker network isolating a /64 inside of my static /56.
This network uses IPv6 direct routing instead of NAT to expose the container caller IP.

Then, I've created my container using this network and I got annouced ips o V4 (Nated) and V6 routed.
Ipv6 is working great and at full speed.
Thanks.

**Comment by k44sh** [comment]
Too fast !
