### ISSUE TITLE
XMLRPC Nginx 502

### ISSUE THREAD

**Issue by fistwho** [k44sh/rutorrent#6]
Hi K44sh,

I try your rutorrent Docker Image. So all seems to work flawless. Only the XMLRPC don't seem to work. I get a 502 Error on port 8000 i route it through Nginxproxymanager. Also if i open it directly on IP:Port - healthcheck say the xmlrpc is working. 

If i open the rpc plugin (https://rutorrent.xxxxx.xx/plugins/rpc/rpc.php) i also got an Error "Link to XMLRPC failed. May be, rTorrent is down?"

I try to add my seedbox to https://addons.mozilla.org/en-US/firefox/addon/xirvik-torrent-to-seedbox-uplo/ for easier handling. 

Did you have an idea what i do wrong?

Sys: Ubuntu 22.04 with latest Docker Version and your latest Docker Image

**Comment by k44sh** [comment]
Hi @fistwho 

I just checked. The XMLRPC port is working fine on my end. Your plugin also works well without needing to specify the XMLRPC
