### ISSUE TITLE
Can't create .torrent file

### ISSUE THREAD

**Issue by motif82** [k44sh/rutorrent#7]
Hi, I created an Unraid docker with your source and have been using it for a few weeks without issue. Great program btw. Today I tried creating a .torrent file for the first time and it is giving me the following error message in the diagnostics box:
 /var/www/rutorrent/plugins/create/mktorrent.sh: line 11: /usr/local/bin/mktorrent: not found
chmod: cannot access '/config/rutorrent/share/settings/tasks/17149484146638093ee69ac5.58690490/temp.torrent': No such file or directory

It looks like the create plugin is enabled and loaded so I'm not sure why it isn't working. I have the same plugin running on my seedbox rutorrent and can create a .torrent on there without any problems. Any insights or advice would be appreciated.

**Comment by k44sh** [comment]
Hi @motif82

Thank you for pointing out this bug. It appears that the path for `mktorrent` is incorrect.
The plugin is looking for the binary in `/usr/local/bin/` while it is actually located in `/usr/bin/`.
Source : /var/www/rutorrent/plugins/create/conf.php`

**Temporary Fix :** You can temporarily fix the issue by creating a symbolic link, for example:

```bash
docker exec -ti rutorrent bash
ln -s /usr/bin/mktorrent /usr/local/bin/mktorrent
```
I'll make a note of this to fix the bug in a future release.

**Comment by motif82** [comment]
Thanks for the fast reply. The symlink worked to fix the issue for now.

**Comment by k44sh** [comment]
New release [v4.3.1](https://github.com/k44sh/rutorrent/commit/0a23980b0f550e450b15b988e50511dc89b4dd4e) 👍🏼
